[general]
logging = false ; Set to true to enable logging

[hue]
bridge_ip = 192.168.x.x
application_key = your-hue-app-key
entertainment_zone_name = Your Zone Name
entertainment_id = ; Optional

; Rename this file to config.ini